middlewares:

  template-static:
    module: trifid-core/middlewares/static.js
    paths: /static
    config:
      directory: file:views

  renderer:
    module: "./lib/plugin-renderer.js"
    config:
      template: "./index.html"
      templateError: "./error.html"
      module: "./index.js"

  handler:
    module: trifid-handler-fetch
    config:
      url: "https://raw.githubusercontent.com/zazuko/tbbt-ld/master/dist/tbbt.nt"
      contentType: "application/n-triples"
      split: true
      cache: true
