server:
  logLevel: debug

middlewares:
  welcome:
    module: trifid-core/middlewares/view.js
    paths: /
    methods: GET
    config:
      path: file:../views/welcome.hbs

  adams:
    paths: /adams/
    module: file:../../index.js

  person:
    paths: /person/
    module: file:../../index.js

  fetch-handler:
    module: trifid-handler-fetch
    config:
      url: file:../data/people.ttl
      contentType: application/n-triples
      split: true
      cache: true
